= Bash scripts for initial setup my RHEL home lab

== Description

Configure two new RHEL machines (a control node and a managed node) for development work.

----
    control node --> managed node
----

It's risky!
This script removes dev friction by doing a whole heap of unsafe things, 
like storing your password in rhel-setup.cfg.
This is for home lab dev use only.

Both machines are assumed to have fresh installs of the RHEL OS.
Maybe the control node is local laptop and the managed node is a nearby PC. 
Or maybe the control node is a jumpbox and the managed node is a VM in a lab.

Set up SSH, sudo, Ansible and other things.
These scripts make hacking simpler by weakening security.
Run this Bash script on the control node.
It uses SSH to get to the other node.

Find the code on Github here. 
  https://github.com/nickhardiman/script-rhel-setup


== What the script does

Configure two RHEL machines - control node and managed node -
by setting up SSH, sudo, Ansible and other things.
This script runs on the control node, 
does a little configuration on this control node and a lot of config on the managed node.

Values like these are set up in rhel-setup.cfg.

----
$CONTROL_USER_NAME@$CONTROL_NODE_IP --(SSH)--> $MANAGED_USER_NAME@$MANAGED_NODE_IP
----

The control node where the script runs is probably your workstation. 
The managed node that the script configures is a freshly installed RHEL machine.
The script uses SSH to connect. 

The rhel-setup.sh bash script pulls in more bash scripts, rhel-setup-*.sh.
The important variables are in rhel-setup.cfg.


== changes to the control node 

Code creates or adds to these files. 

* copy backups to $HOME/$CONTROL_WORK_DIR
* add remote name and address in /etc/hosts
* create private key in $HOME/.ssh/id_rsa (if not already there)
* create public key in $HOME/.ssh/id_rsa.pub
* add remote host key to $HOME/.ssh/known_hosts
* Install Ansible
* Create a CA certificate

== changes to the managed node 

* Define a new prompt in $HOME/.bashrc
* Add control's $HOME/.ssh/authorized_keys
* /etc/sudoers.d/$USER
* create an ansible account $MANAGED_ANSIBLE_NAME
* Add key-based SSH login
* Add passwordless sudo.
* Display FQDN in the Bash prompt. By default, only the host name is shown eg. "[nick@host ~]$ ".
* Install git.
* KVM hypervisor on the three site hosts
* supporting services on site3
* Copy the CA certificate


== Prerequisites

Install RHEL. A minimal install is fine. 

Set up your account on the managed node.
Set a password for your user.
Give your user admin privileges (in the wheel group) so it can use sudo.

Find out what IP address your DHCP server assigned to the managed node.
SSH uses this IP to connect. 
You will add this to rhel-setup.cfg.


== Instructions

SSH to the control node.
Download the Bash script file and its config file from Github to your home directory.
Run the account as your regular user. 
Many commands use sudo, so you do need privilege.

----
curl --fail --remote-name  https://raw.githubusercontent.com/nickhardiman/script-rhel-setup/main/rhel-setup.sh
curl --fail --remote-name  https://raw.githubusercontent.com/nickhardiman/script-rhel-setup/main/rhel-setup.cfg
----

Edit rhel-setup.cfg and add the right values.
eg.  Find out what IP addresses your ISP's router assigned to the managed host, 
and set MANAGED_NODE_IP to this IP adress.

Do not fork https://github.com/nickhardiman/script-rhel-setup then edit the copy. 
That creates the risk of uploading sensitive values to a public place.

----
chmod 600 ./rhel-setup.cfg 
vim ./rhel-setup.cfg 
----

Run the script. 

----
bash ./rhel-setup.sh    
----

Or for wordy debugness, 

----
bash -x ./rhel-setup.sh -v
----

The process should be hands-free from here on in. 
On a good day, SSH and sudo don't ask you to confirm host key or enter a password. 


== part of 

=== third attempt, RHEL lab 

WIP

network of virtual machines on one fresh RHEL 10 host.

take the AAP2 work and break up into less choking chunks

* https://github.com/nickhardiman/script-rhel-setup
* https://github.com/nickhardiman/ansible-playbook-rhel-lab
* https://github.com/nickhardiman/ansible-collection-platform
* https://github.com/nickhardiman/ansible-collection-libvirt
* https://github.com/nickhardiman/ansible-collection-vm-gateway


=== second attempt, AAP2 refarch

couple years ago

network of virtual machines on three fresh RHEL 9 hosts.

worked, but an absolute monster 

* https://github.com/nickhardiman/ansible-playbook-aap-lab
* https://github.com/nickhardiman/ansible-collection-platform

=== first attempt, RHEL lab

few years ago 

network of virtual machines on three fresh RHEL 9 hosts.

* https://github.com/nickhardiman/ansible-playbook-source
* https://github.com/nickhardiman/ansible-playbook-build
* https://github.com/nickhardiman/ansible-playbook-supply
* https://github.com/nickhardiman/ansible-collection-platform
* https://github.com/nickhardiman/ansible-collection-app

